### ISSUE TITLE
The noclip follows true north

### ISSUE THREAD

**Issue by MacGyverPY** [hoiblij/cyberpunknoclip#4]
Ive seen this in other games, the noclip, wont track properly... and it locks the position and so youre forced to move left to go back or vice versa.

**Comment by hoiblij** [comment]
You're probably trying to use a 1.04 trainer on 1.06 Cyberpunk. The rotation addresses are garbage when you try to use the trainer on 1.06, hence why flying is locked to North West South East flying.
