### ISSUE TITLE
Angle and orientation memory addresses incorrect

### ISSUE THREAD

**Issue by andrakis** [hoiblij/cyberpunknoclip#5]
I did a little debugging, and `angle` and `orientation` are always reading as 0. I checked a few memory addresses nearby, but they're all 0.

How did you find their locations? It appears the layout has changed and those values could be anywhere now.

Version 1.06 (GOG)

**Comment by hoiblij** [comment]
I updated this to work for 1.04, so the memory address being garbage in 1.06 is to be expected. From my previous times finding the addresses I know that the Z rotation value is 0-1 between North and West, and 1-0 between West and South. You can use that to find multiple blocks of addresses related to the Z rotation. From there I just browsed the memory to find some addresses I could use.
